### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by infwinston** [lmarena/arena-catalog#1]
Goal: Build a centralized LLM leaderboard for developers

What does a developer care about when building LLM applications?
- Does it solve my task?
- Does it satisfy my service requirement (e.g., latency)?
- How expensive?

Progress
- Our [leaderboard](http://lmarena.ai/leaderboard) evaluates models based on ~2 million pairwise comparisons
- Slice leaderboard in different domains (e.g., coding, math), languages etc
- Millions of leaderboard views

![Image](https://github.com/user-attachments/assets/f5da9d94-48a9-4401-8555-1066b4192850)

Challenges
- Data -> Insights? How to visualize the data?
- Trade-off between cost, speed and performance
- Leaderboard change over time

Roadmap
- General
  - [ ] Search Bar
- Pricing
  - [ ] Add pricing column on leaderboard
  - [ ] Pricing vs score plot
- Capability
  - [ ] Leaderboard over time
  - [ ] Improve overview leaderboard
  - [ ] Data explorer
- Speed
  - [ ] Token per second

[spec](https://docs.google.com/document/d/1dVA2MPlvcl2kLcW3Sb5D_M35iMBpmXmYPXf9sR0L6uM/edit?usp=sharing)
